# on:
#   push:
#     branches: [ master ]
# name: 🚀 Deploy file on SEMIS-FTP
# jobs:
#   web-deploy:
#     name: 🎉 Deploy
#     runs-on: ubuntu-latest
#     steps:
#     - name: 🚚 Get latest code
#       uses: actions/checkout@v2

#     - name: Use Node.js 14
#       uses: actions/setup-node@v2
#       with:
#         node-version: '14'

#     - name: 📂 Sync files
#       uses: SamKirkland/FTP-Deploy-Action@4.2.0
#       with:
#         server: ${{ secrets.FTP_SERVER }}
#         username: ${{ secrets.FTP_USERNAME }}
#         password: ${{ secrets.FTP_PASSWORD }}
#         exclude: |
#           **/.git*
#           **/.git*/**
#           **/node_modules/**


name: Laravel Workflow

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql
          tools: composer:v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Update Dependencies
        run: composer update

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install front-end dependencies
        run: npm install

      - name: Compile assets
        run: npm run production

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            vendor
            node_modules
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-
            ${{ runner.os }}-node-

      - name: Push changes
        run: git push origin master
